spring:
    profiles.active: dev
    application:
      name: java-microservice-client
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true    
---
spring:
    profiles: dev
    oauth:
      user: demo
      password: $2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu
      client-id: demo-client
      client-secret: $2a$04$I9Q2sDc4QGGg5WNTLmsz0.fvGv3OjoZyj81PrSFyGOqMphqfS2qKu
logging:
  file: logs/infra-dev-access.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.infra: DEBUG
    org.hibernate: ERROR
server:
  port: 8080
  servlet:
    context-path: /infra
security:
   oauth2:
      resource:
         filter-order: 3
  
    
 